# Generated by Django 3.1.6 on 2021-02-08 10:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.CharField(max_length=128)),
                ('status', models.BooleanField()),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codingproblems.author')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codingproblems.category')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codingproblems.language')),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codingproblems.codingproblem')),
            ],
        ),
    ]
