# Generated by Django 3.1.6 on 2021-02-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingproblems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
