# Generated by Django 3.1.6 on 2021-02-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingproblems', '0002_solution_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='title',
            field=models.CharField(default='Solution', max_length=128),
        ),
    ]
